---
name: Create packages and test installation

on:
  pull_request:

jobs:
  build-almalinux9:
    name: Build AlmaLinux 9 RPMs
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y rpm-build cmake rpmlint make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v3
        with:
          name: rpms9
          path: |
            build/RPMS/noarch/nagios-*.el9.noarch.rpm

  install-almalinux9:
    name: Install AlmaLinux 9 RPMs
    needs: build-almalinux9
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: rpms9
      - name: Install generated RPMs
        run: |
          # FIXME: remove external repo when UMD5 is available 
          dnf install -y epel-release
          dnf localinstall -y https://github.com/EGI-Federation/nagios-plugins-srm/raw/master/python3-nap-0.1.21-2.el9.noarch.rpm
          dnf localinstall -y nagios-*.rpm
