---
# When a tag is created
# - create a new release from the tag
# - build and attach packages to the release
name: Create packages and release

on:
  push:
    tags:
      - "v*"

jobs:
  almalinux9:
    name: Build AlmaLinux 9 RPMs
    runs-on: ubuntu-latest
    container: almalinux:9
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install build requisites
        run: |
          dnf install -y rpm-build make rsync systemd-rpm-macros
      - name: build rpm
        run: |
          make clean rpm
      - name: Upload RPMs
        uses: actions/upload-artifact@v6
        with:
          name: rpms9
          path: |
            build/RPMS/noarch/nagios-*.el9.noarch.rpm
            build/SRPMS/nagios-*.el9.src.rpm
  release9:
    name: Upload AlmaLinux 9 release artefacts
    permissions:
      contents: write # to upload release asset (softprops/action-gh-release)
    needs: almalinux9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: rpms9
      - name: Find package name
        id: package_name_almalinux9
        run: |
          rpm_path=$(find . -name 'nagios-*.el9.noarch.rpm')
          src_path=$(find . -name 'nagios-*.el9.src.rpm')
          echo "rpm_path=${rpm_path}" >> "$GITHUB_OUTPUT"
          echo "src_path=${src_path}" >> "$GITHUB_OUTPUT"
      - name: Attach AlmaLinux 9 RPMs to the release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ steps.package_name_almalinux9.outputs.rpm_path }}
            ${{ steps.package_name_almalinux9.outputs.src_path }}
